Repository max-romagnoli/System-Telemetry-Agent, pull requests merged in 2024-04, with the labels that each got.

#132 Massimiliano / Prometheus & Exporter running on VMs startup
  .gitignore
  azure/SSH-connection.md
  azure/generate-azure-auth.md
  azure/manual-deployment.md
  azure/prometheus-deployment.md
  azure/scripts/exporter_startup.sh
  azure/scripts/rc.local.sh
  azure/scripts/systemd-prometheus-service
  grafana/conf/provisioning/datasources/prometheus_ds.yaml
  prometheus/sd/azure_targets.json
Labels: infrastructure, Backend, Sprint 4

#135 Liam / Network Fixes
  exporter/collectors/network.py
  exporter/exporter.py
  tests/exporter/collectors/test_network.py
Labels: bug, Backend, Sprint 4

#133 Massimiliano / add a script to simulate different workload scenarios on Azure and trigger alerts
  .gitignore
  alertmanager/alertmanager.template.yml
  azure/manual-deployment.md
  azure/scripts/server_startup.sh
  azure/vmss_ips.txt
  docker/server.py
  docker/simulate_instance_down.sh
  docker/simulate_workload.py
  exporter/collectors/network.py
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  prometheus/alerts.rules.yml
  prometheus/prometheus.yml
Labels: feature, Backend, Frontend, Sprint 4
