Repository max-romagnoli/System-Telemetry-Agent, pull requests merged in 2024-03, with the labels that each got.

#81 Binli / CPU node to stagent
  exporter/collectors/cpu.py
  grafana/conf/provisioning/dashboards/machine.json
Labels: feature, question, Frontend

#75 Victor / disk collectors
  exporter/collectors/disk.py
  exporter/exporter.py
  exporter/metrics.py
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine-more-cpu.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/try.json
  tests/exporter/collectors/test_disk.py
Labels: feature, Backend, Sprint 2

#82 Ayo / memory and network node stagent
  grafana/conf/provisioning/dashboards/machine.json
  tests/exporter/collectors/test_cpu.py
Labels: Sprint 2, Frontend

#95 Claire / Modified __str__ method in cpu.py and related test
  exporter/collectors/cpu.py
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine-more-cpu.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/try.json
  tests/exporter/collectors/test_cpu.py
Labels: bug, Backend, Sprint 3

#101 Liam / Improved Ram Gauges and Testing.
  exporter/collectors/ram.py
  exporter/exporter.py
  exporter/metrics.py
  tests/exporter/collectors/test_ram.py
Labels: feature, Backend, Sprint 3

#108 Leila / CPU utilization by logical & physical core #86
  exporter/collectors/cpu.py
  exporter/exporter.py
  exporter/metrics.py
  tests/exporter/collectors/test_cpu.py
Labels: feature, Backend, Sprint 3

#99 Ayo / ram utilization added without sorting machines
  .gitignore
  docker/Dockerfile
  docker/Dockerfile.node_exporter
  docker/README_Docker.md
  docker/docker-compose.yml
  docker/start_replicas.sh
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine-more-cpu.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/try.json
  prometheus/prometheus.yml
  prometheus/sd/sample.json
Labels: feature, Frontend, Sprint 3

#106 Victor / new test methods for Network metrics
  tests/exporter/collectors/test_network.py
Labels: feature, Backend, Sprint 3

#103 Cindy / Added rate methods, tests and none value checks
  exporter/collectors/network.py
  exporter/exporter.py
  exporter/metrics.py
  tests/exporter/collectors/test_network.py
Labels: feature, Backend, Sprint 3

#91 Binli / change color and style
  .gitignore
  exporter/collectors/network.py
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
Labels: question, Frontend, Sprint 3

#107 Liam / Print statement for CPU temperatures
  docker/docker-compose.yml
  exporter/collectors/cpu.py
Labels: Backend

#126 Ayo / network overview
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
Labels: feature, Frontend, Sprint 4

#128 Leila / gauge from list 110
  exporter/exporter.py
Labels: Backend, Sprint 4
