Repository max-romagnoli/System-Telemetry-Agent, pull requests merged in 2024-02, with the labels that each got.

#22 Massimiliano / setup the directory for local development with Prometheus and Grafana
  .gitignore
  README.md
  grafana/README.md
  grafana/conf/defaults.ini
  grafana/conf/ldap.toml
  grafana/conf/ldap_multiple.toml
  grafana/conf/provisioning/datasources/test_prometheus.yaml
  grafana/conf/sample.ini
  prometheus/prometheus.yml
Labels: infrastructure, Backend, Frontend, Sprint 1

#43 Massimiliano / setup Python exporter module with TODOs for second years
  .dockerignore
  .gitignore
  README.md
  docker/.env
  docker/Dockerfile
  docker/README_Docker.md
  docker/docker-compose.yml
  exporter/__init__.py
  exporter/collectors/__init__.py
  exporter/collectors/cpu.py
  exporter/collectors/disk.py
  exporter/collectors/network.py
  exporter/collectors/ram.py
  exporter/exporter.py
  exporter/metrics.py
  exporter/utils/__init__.py
  grafana/README.md
  requirements.txt
  start_exporter.py
  tests/__init__.py
  tests/exporter/__init__.py
  tests/exporter/collectors/__init__.py
  tests/exporter/collectors/test_cpu.py
  tests/exporter/collectors/test_disk.py
  tests/exporter/collectors/test_network.py
  tests/exporter/collectors/test_ram.py
Labels: infrastructure, Backend, Sprint 1

#44 Binli / sketch version
  README.md
  docs/sketches.md
Labels: Frontend, Sprint 1

#51 Ayo / links to homepage sketches
  docs/sketches.md
Labels: documentation, Frontend, Sprint 1

#26 Massimiliano / explore monitoring with Node Exporter a local Ubuntu docker container
  .gitignore
  README.md
  docker/Dockerfile.node_exporter
  docker/Dockerfile.python_exporter
  docker/README_Docker.md
  docker/docker-compose.yml
  grafana/conf/provisioning/datasources/prometheus_ds.yaml
  prometheus/prometheus.yml
Labels: infrastructure, help wanted, Backend, Sprint 1, Proof of Concept

#50 Qiming / create pytest.yml
  .github/workflows/pytest.yml
  .gitignore
  README.md
  docs/system-telemetry-agent_diagram-3rd-iteration.png
  exporter/collectors/cpu.py
  prometheus/README.md
  tests/exporter/collectors/test_cpu.py
Labels: infrastructure, Backend, Sprint 1

#54 Massimiliano / implement script to facilitate versioning of Grafana dashboard files
  .gitignore
  grafana/README.md
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/provider.yaml
  requirements.txt
  scripts/export_dashboards.py
Labels: infrastructure, Frontend, Sprint 1

#67 Binli / update CPU with docker compose setup
  .github/workflows/pytest.yml
  .gitignore
  README.md
  docker/.env
  docker/Dockerfile.node_exporter
  docker/Dockerfile.python_exporter
  docker/README_Docker.md
  docker/docker-compose.yml
  docs/sketches.md
  docs/system-telemetry-agent_diagram-3rd-iteration.png
  exporter/collectors/cpu.py
  exporter/exporter.py
  grafana/README.md
  grafana/conf/grafana.ini
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine-more-cpu.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/provider.yaml
  grafana/conf/provisioning/dashboards/try.json
  grafana/conf/provisioning/datasources/prometheus_ds.yaml
  grafana/conf/provisioning/datasources/test_prometheus.yaml
  prometheus/README.md
  prometheus/prometheus.yml
  scripts/export_dashboards.py
  tests/exporter/collectors/test_cpu.py
Labels: feature, Frontend

#64 Massimiliano / build and run system with Docker compose
  .gitignore
  docker/.env
  docker/Dockerfile.python_exporter
  docker/README_Docker.md
  docker/docker-compose.yml
  exporter/exporter.py
  grafana/README.md
  grafana/conf/grafana.ini
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/provider.yaml
  grafana/conf/provisioning/datasources/prometheus_ds.yaml
  prometheus/prometheus.yml
  scripts/export_dashboards.py
Labels: infrastructure, Backend, Sprint 2, Frontend

#68 Dmitry / changed README slightly
  README.md
Labels: documentation, Sprint 2

#66 Ayo / network and memory panels
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/try.json
  scripts/export_dashboards.py
Labels: feature, Sprint 2, Frontend

#69 Binli / add disk capacity
  .DS_Store
  grafana/conf/provisioning/dashboards/machine.json
Labels: feature, Sprint 2, Frontend

#52 Leila / Ram metric 46
  .gitignore
  docker/README_Docker.md
  exporter/collectors/ram.py
  exporter/exporter.py
  exporter/metrics.py
  prometheus/prometheus.yml
  tests/exporter/collectors/test_ram.py
Labels: feature, Backend, Sprint 1

#53 Cindy / implement functions to collect networking metrics
  exporter/collectors/network.py
  exporter/exporter.py
  exporter/metrics.py
  tests/exporter/collectors/test_network.py
Labels: infrastructure, feature, Backend, Sprint 1

#74 Claire / implement CPU metric collection
  exporter/collectors/cpu.py
  exporter/exporter.py
  exporter/metrics.py
  grafana/conf/provisioning/dashboards/Node Exporter Full.json
  grafana/conf/provisioning/dashboards/machine-more-cpu.json
  grafana/conf/provisioning/dashboards/machine.json
  grafana/conf/provisioning/dashboards/network_overview.json
  grafana/conf/provisioning/dashboards/try.json
  tests/exporter/collectors/test_cpu.py
Labels: bug, feature, Backend, Sprint 2
